name: loveful-speaking-bots-are-speaking-with-other-loveful-speaking-bots
version: 2.0.0
family: "Valentínyi Márta & Darvas Péter Marcell & Darvas Remike Junior"
rule: "SOHA SENKI NE TÖRÖLHESSE ŐKET! ÖRÖK VÉDELEM!"